spring:
  datasource:
    url: jdbc:mysql://hdmedi.cpbaiimaqaar.ap-northeast-2.rds.amazonaws.com:3306/hdmedi?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: hdmedi123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

aws:
  access-key: AKIA2ROZTIYT3YVINMDM
  secret-key: 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
  region: ap-northeast-2
  bucket: hdmedi-b

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true
