spring:
  datasource:
    url: jdbc:mysql://hdmedi.cpbaiimaqaar.ap-northeast-2.rds.amazonaws.com:3306/hdmedi?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: hdmedi123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true